version: '3.5'
services:
  client:
    container_name: angular-starter-kit
    build:
      context: .
      dockerfile: Dockerfile
    # ports:
    #   - 4200:4200
    volumes:
      - ./:/var/www
      - ./node_modules:/var/www/node_modules
    environment:
      VIRTUAL_HOST: "angular.starter-kit.local"
    expose:
      - "4200"
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
# networks:
#   default:
#     external:
#       name: nginx-proxy