version: '3.5'
services:
  client:
    container_name: angular-starter-kit
    image: abdalem/angular:8.3.5
    # ports:
    #   - 4200:4200
    volumes:
      - ./:/var/www
    environment:
      VIRTUAL_HOST: "angular.starter-kit.local"
    expose:
      - "4200"
    command: ng serve --host 0.0.0.0 --publicHost angular.starter-kit.local
  # nginx-proxy:
  #   image: jwilder/nginx-proxy
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - /var/run/docker.sock:/tmp/docker.sock:ro
networks:
  default:
    external:
      name: nginx-proxy